{
 "title": "Lustre Overview New",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(lustre_stats_total,instance)"
    }
   },
   {
    "name": "fs",
    "label": "Filesystem",
    "query": {
     "query": "label_values(lustre_stats_total, target)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Filesystem capacity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lustre_capacity_kilobytes{target=~\"$fs-OST.*\"})"
    }
   ]
  },
  {
   "title": "Filesystem capacity used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lustre_capacity_kilobytes{target=~\"$fs.OST.*\"}) - sum(lustre_free_kilobytes{target=~\"$fs.OST.*\"})"
    }
   ]
  },
  {
   "title": "Filesystem utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum(lustre_free_kilobytes{target=~\"$fs-OST.*\"})/sum(lustre_capacity_kilobytes{target=~\"$fs-OST.*\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "1 - (sum(lustre_inodes_free{target=~\"$fs-MDT.*\"})/sum(lustre_inodes_maximum{target=~\"$fs-MDT.*\"}))",
     "legendFormat": "meta inodes"
    },
    {
     "expr": "1 - (sum(lustre_inodes_free{target=~\"$fs-OST.*\"})/sum(lustre_inodes_maximum{target=~\"$fs-OST.*\"}))",
     "legendFormat": "data inodes"
    }
   ]
  },
  {
   "title": "Filesystem throughput",
   "type": "graph",
   "description": "* Above 0: Write data bandwidth per filesystem and aggregated\n* Below 0: Read data bandwidth per filesystem and aggregated\n\n* Are there high data bursts?\nNote: \n* max performance for fs1 is xx GB/s\n* max performance for fs2 is yy GB/s",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "repeat": "fs",
   "yaxes": [
    { "format": "Bps", "label": "Read | Write" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(lustre_read_bytes_total{target=~\"$fs-OST.*\"}[2m])) by (job)",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(lustre_write_bytes_total{target=~\"$fs-OST.*\"}[2m])) by (job)",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Filesystem data iops",
   "type": "graph",
   "description": "* Above 0: Write data IOPS per filesystem and overall\n* Below 0: Read data IOPS per filesystem and overall\n\n- The more IOPS the more CPU load and latency. \n- High IOPS, low bandwidth usually means small IO patterns (not great)",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
   "repeat": "fs",
   "yaxes": [
    { "format": "iops", "label": "Read | Write" }
   ],
   "targets": [
    {
     "expr": "sum(rate(lustre_write_samples_total{target=~\"$fs-OST.*\"}[2m])) by (job)",
     "legendFormat": "write"
    },
    {
     "expr": "-sum(rate(lustre_read_samples_total{target=~\"$fs-OST.*\"}[2m])) by (job)",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Filesystem meta iops",
   "type": "graph",
   "description": "Metadata operations per filesystem-type of operation\n\n- Which metadata filesystem has more IOPS?\n- What kind of metadata operation is causing the load?",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
   "repeat": "fs",
   "yaxes": [
    { "format": "ops", "label": "Ops per call" }
   ],
   "targets": [
    {
     "expr": "sum(rate(lustre_stats_total{target=~\"$fs-MDT.*\",client=\"\"}[2m])) by (operation)",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "sum(rate(lustre_stats_total{target=~\"$fs-MDT.*\",client=\"\"}[2m]))",
     "legendFormat": "AGGREGATE"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(client) (lustre_client_stats_total))"
    }
   ]
  },
  {
   "title": "Client IPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "group by(client)(lustre_client_stats_total)"
    }
   ]
  },
  {
   "title": "Client throughput",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "-sum(rate(lustre_client_read_bytes_total{target=~\"$fs-OST.*\"}[2m])) by(client)",
     "legendFormat": "read-{{client}}"
    },
    {
     "expr": "sum(rate(lustre_client_write_bytes_total{target=~\"$fs-OST.*\"}[2m])) by(client)",
     "legendFormat": "write-{{client}}"
    }
   ]
  },
  {
   "title": "Client data iops",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "-sum(rate(lustre_client_read_samples_total{target=~\"$fs-OST.*\"}[2m])) by(client)",
     "legendFormat": "read-{{client}}"
    },
    {
     "expr": "sum(rate(lustre_client_write_samples_total{target=~\"$fs-OST.*\"}[2m])) by(client)",
     "legendFormat": "write-{{client}}"
    }
   ]
  },
  {
   "title": "Client meta iops",
   "type": "graph",
   "description": "Metadata operations per filesystem-type of operation\n\n- Which metadata filesystem has more IOPS?\n- What kind of metadata operation is causing the load?",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "ops", "label": "Ops per call" }
   ],
   "targets": [
    {
     "expr": "sum(rate(lustre_stats_total{target=~\"$fs-MDT.*\",client=~\".+\"}[2m]))by (client)",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "Data throughput per ost",
   "type": "graph",
   "description": "* Above 0: Write data bandwidth per server\n* Below 0: Read data bandwidth per server\n\n* Are all servers equally loaded?\n* Is there any kind of operation generating more load?",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "Bps", "label": "Read | Write" }
   ],
   "targets": [
    {
     "expr": "sum(rate(lustre_write_bytes_total{target=~\"$fs-OST.*\"}[2m])) by(target)",
     "legendFormat": "{{target}}-write"
    },
    {
     "expr": "-sum(rate(lustre_read_bytes_total{target=~\"$fs-OST.*\"}[2m])) by(target)",
     "legendFormat": "{{target}}-read"
    }
   ]
  },
  {
   "title": "Data throughput per oss",
   "type": "graph",
   "description": "* Above 0: Write data bandwidth per server\n* Below 0: Read data bandwidth per server\n\n* Are all servers equally loaded?\n* Is there any kind of operation generating more load?",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "Bps", "label": "Read | Write" }
   ],
   "targets": [
    {
     "expr": "sum(rate(lustre_write_bytes_total{target=~\"$fs-OST.*\"}[2m])) by(instance)",
     "legendFormat": "{{instance}}-write"
    },
    {
     "expr": "-sum(rate(lustre_read_bytes_total{target=~\"$fs-OST.*\"}[2m])) by(instance)",
     "legendFormat": "{{instance}}-read"
    }
   ]
  },
  {
   "title": "Data iops per ost",
   "type": "graph",
   "description": "* Above 0: Write data iops per server\n* Below 0:  Read data iops per server\n\n* Right side (thin lines): CPU load per server\n\n* Usually the more IOPS the more CPU load",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "iops", "label": "Read | Write" }
   ],
   "targets": [
    {
     "expr": "sum(rate(lustre_write_samples_total{target=~\"$fs-OST.*\"}[2m])) by(target)",
     "legendFormat": "{{target}}-write-iops"
    },
    {
     "expr": "-sum(rate(lustre_read_samples_total{target=~\"$fs-OST.*\"}[2m])) by(target)",
     "legendFormat": "{{target}}-read-iops"
    }
   ]
  },
  {
   "title": "Data iops per oss",
   "type": "graph",
   "description": "* Above 0: Write data iops per server\n* Below 0:  Read data iops per server\n\n* Right side (thin lines): CPU load per server\n\n* Usually the more IOPS the more CPU load",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "iops", "label": "Read | Write" }
   ],
   "targets": [
    {
     "expr": "sum(rate(lustre_write_samples_total{target=~\"$fs-OST.*\"}[2m])) by(instance)",
     "legendFormat": "{{instance}}-write-iops"
    },
    {
     "expr": "-sum(rate(lustre_read_samples_total{target=~\"$fs-OST.*\"}[2m])) by(instance)",
     "legendFormat": "{{instance}}-read-iops"
    }
   ]
  },
  {
   "title": "Filesystem ost inodes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lustre_inodes_maximum{target=~\"$fs-OST.*\"})"
    }
   ]
  },
  {
   "title": "Filesystem ost inodes used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lustre_inodes_maximum{target=~\"$fs-OST.*\"}) - sum(lustre_inodes_free{target=~\"$fs-OST.*\"})"
    }
   ]
  },
  {
   "title": "Filesystem mdt inodes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lustre_inodes_maximum{target=~\"$fs-MDT.*\"})"
    }
   ]
  },
  {
   "title": "Filesystem mdt inodes used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lustre_inodes_maximum{target=~\"$fs-MDT.*\"}) - sum(lustre_inodes_free{target=~\"$fs-MDT.*\"})"
    }
   ]
  },
  {
   "title": "Capacity usage per ost",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(lustre_free_kilobytes{target=~\"$fs-OST.*\"}/lustre_capacity_kilobytes{target=~\"$fs-OST.*\"})",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Inodes usage per ost",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (lustre_inodes_free{target=~\"$fs-OST.*\"}/lustre_inodes_maximum{target=~\"$fs-OST.*\"})",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Capacity usage per mdt",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(lustre_free_kilobytes{target=~\"$fs-MDT.*\"}/lustre_capacity_kilobytes{target=~\"$fs-MDT.*\"})",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Inodes usage per mdt",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (lustre_inodes_free{target=~\"$fs-MDT.*\"}/lustre_inodes_maximum{target=~\"$fs-MDT.*\"})",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Meta iops per mdt",
   "type": "graph",
   "description": "* Left (thick lines): IOPS per server",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(lustre_stats_total{client=\"\",target=~\"$fs-MDT.*\"}[2m])) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Meta iops per mds",
   "type": "graph",
   "description": "* Left (thick lines): IOPS per server",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 140 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(lustre_stats_total{client=\"\",target=~\"$fs-MDT.*\"}[2m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Filesystem health check",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "lustre_health_check" }
   ]
  },
  {
   "title": "Filesystem ost degraded",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "lustre_degraded" }
   ]
  }
 ]
}